# 该配置文件仅在本地环境生效，在容器内会被configMap的内容覆盖
debug: true
port: 8080
log_file: ./logs/agent.log
kube_config_file: /root/kube/config

routes:
  - uri: /VideoCodecService/VideoCodec
    limit: 1
    service_name: yt-server-video-codec
    namespace: ai-media
    http_port: 20109
