apiVersion: v1
kind: Service
metadata:
  name: lb-agent
  namespace: ai-media
  labels:
    app: lb-agent
spec:
  ports:
    - name: 8080-8080-tcp
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: lb-agent
